---
Name: silverware-sitemap
---

# Configure Content Controller:

SilverStripe\CMS\Controllers\ContentController:
  required_js:
    - "silverware/sitemap: client/dist/js/bundle.js"
  required_css:
    - "silverware/sitemap: client/dist/styles/bundle.css"
